### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-firenze#78] opened 2016-05-16 06:15 UTC

**Comment by kaspar-naaber** [comment] 2016-06-13 09:47
- [ ] "Main styles -> Maximum width" – not working on "Front page" layout and shows wrong value (content page's 650px).
    - Possible solutions:
         - Disable "Maximum width" controller for front pageddd
         - Add separate controller for "Front page" layouts.
- [ ] "Main styles -> Maximum width" – Minimum value is "650px". Maybe it should be a bit less (400px for example) so user could decrease the default value also (just my opinion).
- [ ] "Primary color" is not changing "Heading" and "Subheading" color. Because some of them are set as `#444` and some are `rgb(68,68,68)` which are actually the same colors in different units. These values should be unified.
- [ ] Looks like "Secondary color" is not changing anything. It probably should be the color of the menus menust and content text?
- [ ] There's no "background color" in "Front page" layout so displayng this controller on "Front page" is redundant.
- [ ] "Bebas Neue" supports only capitlized letters so "text-transform" option should be removed from titles and other areas that uses this font.

**Comment by kaspar-naaber** [comment] 2016-06-21 11:19
Second round testing
- [ ] Why is there two colors for "dark" and "light" background? The other one seems to change nothing:
![screenshot 2016-06-21 13 33 18](https://cloud.githubusercontent.com/assets/3191867/16226573/c0dcfe12-37b4-11e6-91d1-1c9edb368d21.png)

- [ ] Color schemes are not applied to the front page header, menu items and horizontal lines:
![bg](https://cloud.githubusercontent.com/assets/3191867/16226634/0f991a04-37b5-11e6-99c7-62b837e6cd01.gif)

- [ ] Firenze has the "widescreen mode" where all content area elements should be 1.4 times bigger. For example `h1` font size under 1400px wide screens is 36px, but starting from 1401px it is 36x1.4=50.4 (50px rounded).
-- You already have done something similar to the `body` and `.content-formatted`:

```
@media screen and (max-width: 1400px)
body, .content-formatted {
  font-size: calc(var(--content-font-size) * 0.8);
}
```

But you should hold the same line as the main stylesheet uses. For example:

```
body {
  font-size: var(--some-variable);
}

@media screen and (min-width: 1400px) {
  body {
    font-size: calc(var(--some-variable) * 1.4);
  }
}
```

- [ ] Line heights are still in `em` (should be unitless).

- [ ] Light scheme button has no styles.
![jun-21-2016 13-50-04](https://cloud.githubusercontent.com/assets/3191867/16227118/96b047c2-37b7-11e6-8b77-f64300794769.gif)

- [ ] "Front page" layout "FORM" controllers doesn't change the color of the form text. But since the front page has a color scheme based colors maybe it is better to remove "FORM" section from the "Front page" layout?

- [ ] Check the generated "components". There might be some deprecated files (for example: "template-cs-content-ver2.tpl":
![screenshot 2016-06-21 14 03 49](https://cloud.githubusercontent.com/assets/3191867/16227422/1e693efc-37b9-11e6-94f3-cab6031ba36d.png)

- [ ] "Main styles -> Maximum width" – Minimum value is "650px". Maybe it should be a bit less (400px for example) so user could decrease the default value also (just my opinion).
-- This one was marked as complete but the minimum value is still "650px". Is it the way it supposed to be or was closed by mistake?

- [ ] "Sub menu" hover color changes the "active" state color (they should not be binded).

- [ ] Link element doesn't have hover effect (`opacity: .8` in `main.css` and `main.min.css`.

- [ ] "BUTTON" section has obsolete "line-height" controller.

- [ ] "FOOTER" and "FORM" order should be switched ("FOOTER" is the last section in design editor).

**Comment by kaspar-naaber** [comment] 2016-06-21 11:21
Pleas check the first round testing tasks also. There are some which are still open. Close them if they should be fixed.

**Comment by kaspar-naaber** [comment] 2016-07-07 15:54
**Third round testing:**

- [ ] Modifying main font size breaks admin bar:
![jul-07-2016 18-36-50](https://cloud.githubusercontent.com/assets/3191867/16659209/d0f97e64-4471-11e6-8691-e8ca0dd18083.gif)

-

- [ ] Wide-screen rules (1.4 times bigger) are not applied to **headings**.
- [ ] Main menu hover effects do not apply (**Front page** layout).
- [ ] Only option in the **HEADER** section in **Front page** is **Main menu**. Maybe the **Main menu** should be the main section in this layout?

More coming... 👍

**Comment by kaspar-naaber** [comment] 2016-07-13 07:27
**Fourth round testing:**
- [ ] "_CONTENT -> Text -> Line height_" property has _em_ units but should be unitless.
- [ ] "_HEADER -> Main menu -> Line height_" property has _em_ units but should be unitless.
- [ ] "_HEADER_" should be the second section in the list.
- [ ] There are at least two additional variables that also changes the _topbar_'s height: `--font-two` and `--header-mainmenu-line-height`. Those should be added to the JS function's `relevantVariables` array aswell.

-

- [ ] Active menu item in _topbar_ is by default with the same color as the _header's_ menu item.

![screenshot 2016-07-13 10 03 34](https://cloud.githubusercontent.com/assets/3191867/16794888/0a9ad418-48e3-11e6-9a0d-98a385a7e6aa.png)

It should be white by default and for modifying I'll see three options:
  1. It is always _white_ and not editable by design editor.
  2. The color changes with the `--color-bg` variable (which is white by default). In that case the `--color-bg` is not the most proper name for this variable because it might not only be related to _content's background_.
  3. _Topbar_ will get it's own _SECTION_ and it's background, menu items etc. can be changed from there.
     * I have mixed feelings about this solution. It might be a good idea to separate this menu styles from _header_ menu because if I change the header menu color or font size or etc, I might want to leave the _topbar_ as it was by default. On the other hand the _topbar_ is quite a hidden feature and user might not understand what he/she is changing. What do you think?

-

- [ ] Whether you choose the second solution from the previous bug or not it might still be a good ide to change the `--color-bg` variable name to `--color-third` because as it shows it might not be relevant only to the content's background if we add some features in the future.
  * It would make sense to name it `--content-color-bg` or something similar if it was in the _CONTENT_ section and changes only the contents's background but in that case it is in the _MAIN STYLES_ section and should have more generic name.

-

- [ ] There's no point for showing _CONTENT_ section in _Blog listing_ and _Blog article_ view (There are no simple _content areas_ and these pages don't have _Sub menu_ either. Only _BLOG_ section makes sense:

![screenshot 2016-07-13 10 22 21](https://cloud.githubusercontent.com/assets/3191867/16795028/cece05d0-48e3-11e6-939c-1d129f823300.png)

-

- [ ] "_BLOG -> Text_" and "_BLOG -> Links_" controllers are not working in _Blog listing_ view.

**Comment by SSirjes** [comment] 2016-07-13 12:05
* [ ] Blog tag'ile tõlge

**Comment by kaspar-naaber** [comment] 2016-07-14 07:41
**Fifth round testing:**
- [ ] Instead of writing this long "sausage" it would be a good idea to write conditionals only for different parts of the code:

Replace this:
```
  {% if front_page %}
    {% include "template-cs-main-styles-front" %}
    {% include "template-cs-header-front" %}
    {% include "template-cs-content-front" %}
    {% include "template-cs-headings-front" %}
    {% include "template-cs-button-front" %}
    {% include "template-cs-table-front" %}
  {% endif %}

  {% if common_page %}
    {% include "template-cs-main-styles" %}
    {% include "template-cs-header" %}
    {% include "template-cs-content" %}
    {% include "template-cs-headings" %}
    {% include "template-cs-button" %}
    {% include "template-cs-table" %}
    {% include "template-cs-form" %}
  {% endif %}

  {% if blog_article %}
    {% include "template-cs-main-styles" %}
    {% include "template-cs-header" %}
    {% include "template-cs-blog-article" %}
    {% include "template-cs-headings" %}
    {% include "template-cs-button" %}
    {% include "template-cs-table" %}
    {% include "template-cs-form" %}
  {% endif %}

  {% if blog_list %}
    {% include "template-cs-main-styles" %}
    {% include "template-cs-header" %}
    {% include "template-cs-blog-list" %}
    {% include "template-cs-headings" %}
    {% include "template-cs-button" %}
    {% include "template-cs-table" %}
    {% include "template-cs-form" %}
  {% endif %}
```

with something like that:

```
  {% if front_page %}
    {% comment %}Front page lives its own life so it has completely separate list{% endcomment %}
    {% include "template-cs-main-styles-front" %}
    {% include "template-cs-header-front" %}
    {% include "template-cs-content-front" %}
    {% include "template-cs-headings-front" %}
    {% include "template-cs-button-front" %}
    {% include "template-cs-table-front" %}
  {% else %}
    {% comment %}These two are all same for common page, blog listing and blog article layouts. So there's no point to repeat the code{% endcomment %}
    {% include "template-cs-main-styles" %}
    {% include "template-cs-header" %}
    
    {% comment %}These sections are all diffetent for common page, blog listing and blog article layouts. So we add conditional statements for these.{% endcomment %}
    {% if common_page %}
      {% include "template-cs-content" %}
    {% elsif blog_list %}
      {% include "template-cs-blog-list" %}
    {% elsif blog_article %}
      {% include "template-cs-blog-article" %}
    {% endif %}
    
    {% comment %}These four are all same for common page, blog listing and blog article layouts. So there's no point to repeat the code.{% endcomment %}
    {% include "template-cs-headings" %}
    {% include "template-cs-button" %}
    {% include "template-cs-table" %}
    {% include "template-cs-form" %}
  {% endif %}
```
NB! Don't forget to test if it works and also remove my `{% comment %}-s`.

-

More coming... (maybe) :)

**Comment by kaspar-naaber** [comment] 2016-07-15 08:16
**Sixth round testing:**
Found some additional stuff. I'll fix them by myself.

- [ ] Front page layout dark and light background controllers have only on option. So there's no need for expand/collapse there.
- [ ] Unbind button colors from main style colors.

**Comment by SSirjes** [comment] 2016-08-01 06:41
* [ ] Front page: link hover font-weight is smaller 
Video: http://www.giphy.com/gifs/l0MYMdLLKbEST8TSw

**Closed** 2016-12-22 09:46 UTC
Labels: feature
