### ISSUE TITLE
In mobile search don't close with "X" 

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-firenze#68] opened 2015-10-28 14:11 UTC
When I open search and I want close search form from "X", what is next to search icon, then it does not close. It seems, that it occurs only with small screens. I tested with iPod.

![screen shot 2015-10-28 at 15 58 57](https://cloud.githubusercontent.com/assets/13623224/10790599/dd641c2e-7d8c-11e5-8265-c2ded6ed572b.png)

**Comment by kaspar-naaber** [comment] 2016-01-05 12:26
Couldn't reproduce. Might be fixed with some other issue. Please reopen if the problem still exists.

**Closed by kaspar-naaber** 2016-01-05 12:26 UTC
Labels: bug
